name: flutter_ranking
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  actions_toolkit_dart: ^0.5.1
  freezed_annotation: ^1.1.0
  http: ^0.13.1
  json_annotation: ^4.4.0
  oauth2: ^2.0.0
  path: ^1.8.0
  pubspec: ^2.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.0.1
  freezed: ^1.1.1
  json_serializable: ^6.1.3