name: flutter_ranking
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  http: ^0.13.1
  intl: ^0.18.0
  twitter_api_v2: ^4.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
