name: Auto Update Flutter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,2,4,6,8,10,12,14,16,18,20,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: dart pub get

      - name: Build Ranking
        run: dart run
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          RANKING_TYPE: flutter

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Yay, Flutter Ranking has been updated 👑✨
