name: Auto Update

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: dart pub get

      - name: Build Ranking
        run: dart run

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Yay, Flutter Ranking has been updated 👑✨
