name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: dart pub get

      - name: Build Flutter Ranking
        run: dart run
        env:
          GITHUB_BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          RANKING_TYPE: all

      - name: Build Widget Ranking
        run: dart run
        env:
          GITHUB_BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          RANKING_TYPE: only_flutter_widget

      - name: Build Dart Ranking
        run: dart run
        env:
          GITHUB_BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          RANKING_TYPE: exclude_flutter_widget

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Scheduled] Yay, Flutter Ranking has been updated 👑✨" 
          commit_user_name: myConsciousness
          commit_user_email: contact@shinyakato.dev
          commit_author: myConsciousness <contact@shinyakato.dev>
