name: Auto Update Dart SDK Only

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2,5,8,11,14,17,20,23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: dart pub get

      - name: Build Ranking
        run: dart run
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          RANKING_TYPE: dart

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Yay, Flutter Ranking for Dart SDK Only has been updated 👑✨
